# Use root/example as user/password credentials
version: '3.1'

services:

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: bucketeer_pass
            POSTGRES_DB: bucketeer_db
    networks: 
      - network1

  adminer:
    image: adminer
    restart: always
    container_name: reading-list-adminer
    ports:
      - 8083:8080
    networks: 
      - network1

  reading-list-api:
    image: ${DOCKER_REGISTRY-}reading-list-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - docker.env
    networks: 
      - network1

volumes:
  data:

networks:
  network1:
